# Generated by Django 6.0.5 on 2026-05-28 23:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gmailcredential',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='gmailcredential',
            old_name='access_token',
            new_name='encrypted_access_token',
        ),
        migrations.RenameField(
            model_name='gmailcredential',
            old_name='refresh_token',
            new_name='encrypted_refresh_token',
        ),
        migrations.RemoveField(
            model_name='synclog',
            name='user',
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='email',
            field=models.EmailField(default=None, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='last_history_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='name',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='scopes',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='gmailcredential',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('disconnected', 'Disconnected'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='synclog',
            name='gmail_connection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='gmail_integration.gmailcredential'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gmailcredential',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gmailcredential',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gmail_cred', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='synclog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='gmailcredential',
            table='gmail_credentials',
        ),
        migrations.AlterModelTable(
            name='synclog',
            table='synclog',
        ),
    ]
