# Generated by Django 6.0.5 on 2026-06-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmail_integration', '0002_alter_gmailcredential_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmailcredential',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
